server:
  port: 8314

spring:
  application:
    name: fiz-eureka-server

# eureka by default will register itself as a client. So, we need to set it to false.
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8314/eureka
